// Code generated by "stringer -type=Code"; DO NOT EDIT.

package action

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Connected-1]
	_ = x[Disconnected-2]
	_ = x[NetworkDisconnect-3]
	_ = x[Damaged-4]
	_ = x[Destroyed-5]
	_ = x[ShotDown-6]
	_ = x[Achieved-7]
	_ = x[Afire-8]
	_ = x[Wrecked-9]
	_ = x[Crashed-10]
	_ = x[SoftLanding-11]
	_ = x[FinalBlow-12]
}

const _Code_name = "UnknownConnectedDisconnectedNetworkDisconnectDamagedDestroyedShotDownAchievedAfireWreckedCrashedSoftLandingFinalBlow"

var _Code_index = [...]uint8{0, 7, 16, 28, 45, 52, 61, 69, 77, 82, 89, 96, 107, 116}

func (i Code) String() string {
	if i < 0 || i >= Code(len(_Code_index)-1) {
		return "Code(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Code_name[_Code_index[i]:_Code_index[i+1]]
}
