// Code generated by "stringer -type=tokenType"; DO NOT EDIT.

package hudmsg

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[unknownType-0]
	_ = x[clanTagType-1]
	_ = x[playerNameType-2]
	_ = x[vehicleType-3]
	_ = x[actionType-4]
	_ = x[achievementType-5]
}

const _tokenType_name = "unknownTypeclanTagTypeplayerNameTypevehicleTypeactionTypeachievementType"

var _tokenType_index = [...]uint8{0, 11, 22, 36, 47, 57, 72}

func (i tokenType) String() string {
	if i < 0 || i >= tokenType(len(_tokenType_index)-1) {
		return "tokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokenType_name[_tokenType_index[i]:_tokenType_index[i+1]]
}
